### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by carlitose** [tudinhacoustic/tiktok-shop#1]
Hi @tudinhacoustic,
I wanted to express my appreciation for your project. I have been attempting to utilize your module for the TikTok shop, but I keep receiving an error stating "invalid signature." Have you tested your code for publishing or using it with one of the calls mentioned in this link: https://partner.tiktokshop.com/doc/page/63fd7426715d622a338c4b31?external_id=63fd7426715d622a338c4b31?
Thanks!
Carlo

**Comment by tudinhacoustic** [comment]
Dear @carlitose,

As you mentioned, I had a quick test with my module, but it worked. Please provide your complete TikTok URL request and check your URL parameters carefully. For example:

"https://open-api.tiktokglobalshop.com/api/shop/get_authorized_shop?access_token=ROW_Oxxx&app_key=6a6mxxx3&shop_id=&timestamp=1698491929&version=202212"

As you can see, the parameter "shop_id=" is optional. If your TikTok shop URL includes it, please add it to the URL variable as well. For example:

const yourUrl = "https://open-api.tiktokglobalshop.com/api/shop/get_authorized_shop?access_token=ROW_Oxxx&app_key=6a6mxxx3&shop_id=&timestamp=1698491929&version=202212";

Hope this helps you
Check the result: https://drive.google.com/file/d/1r_J2yj1wVmsu707noTiVnUjja3a4HAhY/view?usp=sharing

**Comment by carlitose** [comment]
Thank you @tudinhacoustic I try to check it

**Comment by carlitose** [comment]
@tudinhacoustic I have submitted a PR for incorporating tiktok shop calls. I am eager to contribute to your repository if you are interested.

**Comment by tudinhacoustic** [comment]
Thank you @carlitose, if it has any 'invalid signature' errors while using this module, please let me know.

**Comment by carlitose** [comment]
Yes, it works! Now I am going to fix my pull request.
Thank you @tudinhacoustic
